### ISSUE TITLE
ci: upgrade to Bazel 0.27.0

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#116]
Bazel released a new version. CI currently runs on 0.26.1.

There is a starter [PR](https://github.com/lyft/envoy-mobile/pull/103) to do so. However, we encountered build issues with Android NDK on Linux due to missing `pipe2` definitions.

**Comment by jin** [comment]
Bazel 0.27 comes with support for Android NDK 19 and 20, which promoted some warnings into errors according to the NDK build system maintainers guide. These were promoted because they could lead into bugs with NDK-Clang compilations. 

See https://github.com/bazelbuild/bazel/pull/8524 and https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/rules/android/ndkcrosstools/r19/AndroidNdkCrosstoolsR19.java;l=65-100?q=androidndkcrosstoolsR19 for more information.

**Comment by junr03** [comment]
Getting back to this. Yep, @jin that is what I am seeing:

```/var/tmp/_bazel_josenino/9e680707426f56f890add48ff19d437d/execroot/__main__/external/com_github_libevent_libevent/evutil.c:2637:6: error: implicit declaration of function 'pipe2' is invalid in C99 [-Werror,-Wimplicit-function-declaration]```

**Comment by rebello95** [comment]
Just adding a note here - https://github.com/lyft/envoy-mobile/pull/155 is on hold until we update to bazel 0.27.0

**Comment by keith** [comment]
Filed https://github.com/bazelbuild/rules_foreign_cc/issues/289 upstream about our current inability to easily check in CMake configuration if we're targeting Android. If we could do that I believe this patch would be enough https://github.com/libevent/libevent/pull/850

In the meantime I will try and do this in envoy only for Android

**Comment by keith** [comment]
Here's the temporary envoy fix https://github.com/envoyproxy/envoy/pull/7497

**Comment by keith** [comment]
This gives us that fix https://github.com/lyft/envoy-mobile/pull/236

**Comment by keith** [comment]
https://github.com/lyft/envoy-mobile/pull/246
