### ISSUE TITLE
platform: move tests to top-level test/ dir

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#408]
@goaway and I were conversing, and believe that the current platform tests that are buried in the library/swift<or>kotlin/test dirs could be moved out to the top-level test/ directory so that all of the project testing is in one place.

wdyt @buildbreaker @rebello95

**Comment by buildbreaker** [comment]
Is the idea to have a `test/` with all the tests there?

I generally like having the source/test files closer together primarily because it makes navigating from source to test easier. In *some* sense, the tests are a "how-to" guide to using the class it's associated with

What's the motivation for centralizing it?
