### ISSUE TITLE
ci: fix coverage & re-enable job

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#863]
In #861 envoy was bumped. It included https://github.com/envoyproxy/envoy/pull/10909. https://github.com/envoyproxy/envoy/pull/10909 was a major overhaul of coverage, and I believe envoy mobile's use was broken per: https://github.com/lyft/envoy-mobile/runs/711200768

**Comment by rebello95** [comment]
I'm temporarily disabling coverage for now since it's blocking PRs: https://github.com/lyft/envoy-mobile/pull/866

I spent a few minutes looking into fixing the breakage from https://github.com/envoyproxy/envoy/pull/10909, but it looks like the fix won't be trivial since we [rely on](https://github.com/lyft/envoy-mobile/blob/f50aaa57033decf68d2e961f7716ecb9a5f42402/test/coverage/run_coverage.sh#L6-L8) `EXTRA_QUERY_PATHS` and `ONLY_EXTRA_QUERY_PATHS` (the latter of which was [added upstream](https://github.com/envoyproxy/envoy/commit/9931239df99abda9ec69d450177730826d985c25) by @junr03 recently), and the file that used those was deleted in the above PR.
